//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlockBuster
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieGenre
    {
        public int MovieGenreId { get; set; }
        public Nullable<int> GenreID { get; set; }
        public Nullable<int> MovieID { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual Movie Movie { get; set; }
    }
}
